apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carrefour-mcommerce-push
  file_path: envs/local/Dockerfile
  description: Testes gerais
spec:
  type: service
  lifecycle: qa
  owner: platform
  system: system:default/base-system
